# client start/stop scripts listed in this file are launched on start and stop.
#
# names refer to any kind of executable with paths relative to folder
# 'clients' or its subfolders, and corresponding options, if any.


# Don't name this mpd.py since it could interfere with mpd module.
#mpd:
#    start:  mpd/mpd_load.py start
#    stop:   mpd/mpd_load.py stop

#DVB:
#    start:  DVB/DVB_load.py start
#    stop:   DVB/DVB_load.py stop

#netjack:
#    start:  netjack_load.py

#stream_loop:
#    start:  stream_loop.py start

# zita-cd:
#     start:  zita-cd start
#     stop:   zita-cd stop

# librespot:
#     start:  librespot start
#     stop:   librespot stop
