## values cannot be void
## numbers: assign "none" to not set
## strings: assign "''" to not set



## hardware

loudspeaker: JBL_LSR305


## misc

# delay between commands (seconds)
command_delay: 1
# use fixed initial state, instead of last saved state
use_state_init: true
# when changing sources use associated phase_eq setting
use_source_phase_eq: false
# mute output before some commands
do_mute: true



## jack audio ports

# source selector will connect sources ports to this ports in order.
# each group of ports is a space separated string.

audio_ports:
    - cpal_client_in:in_0 cpal_client_in:in_1
    # - system:playback_1 system:playback_2
    # - stream_loop:input_1 stream_loop:input_2


## core

# server
# verbose: 0 (minimal), 1 (informative), 2 (debug)

verbose: 1
# address and port
# 0.0.0.0 listen to all net connections
# 127.0.0.1 listen only to local connections
control_address: 0.0.0.0
control_port: 9999

# jack
# omit fs (managed in startaudio.py, taken from loudspeaker config)

jack_command: /usr/bin/jackd --silent -R -dalsa -p512 -n 3 -d hw:USB,0

# camilladsp
# for options see https://github.com/HEnquist/camilladsp#command-line-options.
# omit config file (managed in startaudio.py, taken from loudspeaker config).
# fs is taken from loudspeaker config and overrides camilladsp.yml.

camilladsp_command: /home/predic/bin/camilladsp --logfile /dev/null
# use this for warnings to appear on screen:
# camilladsp_command: /home/predic/bin/camilladsp.
websocket_address: 127.0.0.1
websocket_port: 1234
