# Recording equalizer config

"1":
    f.eq:
        description: 'dummy eq for classical'
        type: Conv
        parameters:
            type: Dummy
            length: 1
            
"2":
    f.eq:
        description: 'dummy eq for pop'
        type: Conv
        parameters:
            type: Dummy
            length: 1
