balance: 0.0
bass: 0.0
channels: lr
channels_flip: 'off'
drc: 'on'
drc_set: '1'
eq: 'off'
eq_filter: '1'
level: -12.0
loudness: 'off'
loudness_ref: 0.0
mute: 'off'
phase_eq: 'on'
polarity: 'off'
polarity_flip: 'off'
solo: lr
stereo: normal
tones: 'off'
treble: 0.0
