balance: 0.0
bass: 0.0
channels: lr
channels_flip: 'off'
clamp: 'on'
drc: 'off'
drc_set: '1'
eq: 'off'
eq_filter: '1'
level: -32.0
loudness: 'off'
loudness_ref: 0.0
mute: 'off'
phase_eq: 'off'
polarity: 'off'
polarity_flip: 'off'
solo: lr
source: analog
sources: 'on'
stereo: normal
tones: 'off'
treble: 0.0
