# DVB-T client config

# please respect indentation when editing

# mplayer start command line:
# mplayer aditional options set in ~/.mplayer/config
start_command: /usr/bin/mplayer

# mplayer kill command line:
stop_command: pkill -f /usr/bin/mplayer

# DVB source name in ~/pre.di.c/sources.yml
DVB_source_name: dvb

# play preset on start
# set preset as "last" for last played channel
play_on_start: true
preset: 6

# ancillary filenames
state_filename: state.yml
presets_filename: presets.yml
# commands FIFO filename
# option -input file={dvb_fifo} is added in program
fifo_filename: DVB_fifo

# address and port
# 0.0.0.0 listen to all net connections
# 127.0.0.1 listen only to local connections
control_address: 0.0.0.0
control_port: 9998
